version = 1
SPDX-PackageName = "wrp-go"
SPDX-PackageSupplier = "Weston Schmidt <weston_scmidt@alumni.purdue.edu>"
SPDX-PackageDownloadLocation = "https://github.com/xmidt-org/wrp-go"

[[annotations]]
path = ".golangci.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "go.mod"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "go.sum"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "AUTHORS"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".whitesource"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "format_string.go"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "messages_gen.go"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "messagetype_string.go"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "qoslevel_string.go"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"
